In [ ]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse import csr_matrix

# Create a sparse matrix of shape (3, 4) with integer data type
mtx = csr_matrix((3, 4), dtype=np.int8)

# Convert sparse matrix to dense format and print it
print(mtx.todense())


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
import numpy as np
from scipy.sparse import csr_matrix

user_ids = np.array([1, 2, 3, 4, 6, 6])
movie_ids = np.array([7, 8, 9, 7, 8, 10])
binary_ratings = np.array([1, 1, 1, 1, 1, 1])


# Create a sparse matrix
num_users = user_ids.max()
num_movies = movie_ids.max()
sparse_matrix = csr_matrix((binary_ratings, (movie_ids - 1, user_ids - 1)), shape=(num_movies, num_users))

# Filter out zero rows
non_zero_row_indices = sparse_matrix.getnnz(axis=1) > 0
sparse_matrix = sparse_matrix[non_zero_row_indices]

# Convert filtered sparse matrix to dense
filtered_sparse_matrix.todense()

matrix([[1, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 1],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1]])

array([0, 0, 1, 1, 2, 2])